version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'

# version: '3'
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     ports:
#       - '3000:3000'
#     volumes:
#       - /home/node/app/node_modules
#       - .:/home/node/app
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /home/node/app/node_modules
  #     - .:/home/node/app
  #   command: ["npm","run","test"]