# FROM node:18-alpine3.16

# RUN mkdir -p /home/node/app

# WORKDIR /home/node/app

# COPY package*.json ./

# RUN npm install
# RUN mkdir /home/node/app/node_modules/.cache && chmod -R 777 /home/node/app/node_modules/.cache

# COPY . ./home/node/app
# CMD ["npm", "run", "start"]

#https://stackoverflow.com/questions/67087735/eacces-permission-denied-mkdir-usr-app-node-modules-cache-how-can-i-creat

# docker run -p 3000:3000 -v /home/node/app/node_modules -v $(pwd):/home/node/app frontend

FROM node:18-alpine3.16
USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
CMD ["npm", "start"]
