version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm","run","test"]
    
    



# version: '3'
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     ports:
#       - '3000:3000'
#     volumes:
#       - /home/node/app/node_modules
#       - .:/home/node/app